First version in golang implementation
tagomoris/unlinker pull request #1
Opened 2018-06-22 08:59 UTC by tagomoris

2018-06-22 09:34 UTC, tagomoris commented
@narse Could you review this tool?

2018-06-25 03:07 UTC, nurse requested changes

2018-06-25 03:07 UTC, nurse commented on main.go
> +	result := strings.Repeat(format, 1)
This copies format to avoid changing the string in accident.
But Go's string is immutable; it can be just result := format, or reusing the variable format.

2018-06-25 03:07 UTC, nurse commented on main.go
> +	var err error
These definition can move inside for loop

2018-06-25 03:07 UTC, nurse commented on main.go
> +	var err error
Why did you define these variables explicitly?

2018-06-25 03:07 UTC, nurse commented on main.go
> +	if strings.Index(c.PathPattern, "*") == -1 {
You can use `strings.Contains` or `strings.Count`.

2018-06-25 06:16 UTC, tagomoris commented on main.go
> +	var err error
Good point.

2018-06-25 06:16 UTC, tagomoris commented on main.go
> +	var err error
It's just my mistake 👍

2018-06-25 06:32 UTC, tagomoris commented
I've pushed commits for your review comments.
@nurse Could you check again?

2018-06-25 09:26 UTC, nurse approved these changes
LGTM with a comment about test

2018-06-25 09:26 UTC, nurse commented on main_test.go
> +	dir, err := ioutil.TempDir("", "unlinker")
As documented [`ioutil.TempDir`](https://golang.org/pkg/io/ioutil/#TempDir)'s tempdir needs clean up by caller.
https://twitter.com/objectxplosive/status/1011093725076905984

2018-06-26 05:19 UTC, tagomoris commented
@nurse Thank you! I added another commit to cleanup temp directories.

2018-06-26 05:21 UTC, merged